-- COMMONS
vim.api.nvim_set_hl(0, "NeogitObjectId", { fg = "#ffb100" })
vim.api.nvim_set_hl(0, "NeogitBranch", { fg = "#ffb100" })
vim.api.nvim_set_hl(0, "NeogitBranchHead", { fg = "#ffb100", bold = true })
vim.api.nvim_set_hl(0, "NeogitRemote", { fg = "#c05746" })
vim.api.nvim_set_hl(0, "NeogitSubtleText", { fg = "#c05746" })
vim.api.nvim_set_hl(0, "NeogitSectionHeader", { fg = "#ffb100" })
vim.api.nvim_set_hl(0, "NeogitTagName", { fg = "#c05746" })
-- POPUPS
vim.api.nvim_set_hl(0, "NeogitPopupActionKey", { fg = "#ffb100" })
vim.api.nvim_set_hl(0, "NeogitPopupSectionTitle", { fg = "#c05746" })
vim.api.nvim_set_hl(0, "NeogitPopupSwitchKey", { fg = "#79ADB1" })
vim.api.nvim_set_hl(0, "NeogitPopupConfigKey", { fg = "#eb88af" })
vim.api.nvim_set_hl(0, "NeogitPopupOptionKey", { fg = "#79ADB1" })
-- GRAPH
vim.api.nvim_set_hl(0, "NeogitGraphBlack", { fg = "#071013" })
vim.api.nvim_set_hl(0, "NeogitGraphBlackBold", { fg = "#071013", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldBlack", { fg = "#071013", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphRed", { fg = "#c05746" })
vim.api.nvim_set_hl(0, "NeogitGraphRedBold", { fg = "#c05746", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldRed", { fg = "#c05746", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphGreen", { fg = "#9AE2A5" })
vim.api.nvim_set_hl(0, "NeogitGraphGreenBold", { fg = "#9AE2A5", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldGreen", { fg = "#9AE2A5", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphYellow", { fg = "#ffb100" })
vim.api.nvim_set_hl(0, "NeogitGraphYellowBold", { fg = "#ffb100", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldYellow", { fg = "#ffb100", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBlue", { fg = "#79ADB1" })
vim.api.nvim_set_hl(0, "NeogitGraphBlueBold", { fg = "#79ADB1", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldBlue", { fg = "#79ADB1", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphPurple", { fg = "#AD498C" })
vim.api.nvim_set_hl(0, "NeogitGraphPurpleBold", { fg = "#AD4982", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldPurple", { fg = "#AD4982", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphCyan", { fg = "#1CCAC4" })
vim.api.nvim_set_hl(0, "NeogitGraphCyanBold", { fg = "#1CCAC4", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldCyan", { fg = "#1CCAC4", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphWhite", { fg = "#f2EDEB" })
vim.api.nvim_set_hl(0, "NeogitGraphWhiteBold", { fg = "#f2edeb", bold = true })
vim.api.nvim_set_hl(0, "NeogitGraphBoldWhite", { fg = "#f2edeb", bold = true })
-- DIFFS
vim.api.nvim_set_hl(0, "NeogitDiffAdd", { fg = "#9AE2A5", bold = true })
vim.api.nvim_set_hl(0, "NeogitDiffDelete", { fg = "#c05746", bold = true })
vim.api.nvim_set_hl(0, "NeogitDiffContext", { fg = "#65696A" })
vim.api.nvim_set_hl(0, "NeogitDiffHeader", { fg = "#ffb100", bold = true })
vim.api.nvim_set_hl(0, "NeogitHunkHeader", { bg = "#11262D" })
vim.api.nvim_set_hl(0, "NeogitDiffAddHighlight", { fg = "#9AE2A5", bold = true })
vim.api.nvim_set_hl(0, "NeogitDiffDeleteHighlight", { fg = "#c05746", bold = true })
vim.api.nvim_set_hl(0, "NeogitDiffContextHighlight", { fg = "#65696A", bold = true })
vim.api.nvim_set_hl(0, "NeogitDiffHeaderHighlight", { fg = "#ffb100", bold = true })
vim.api.nvim_set_hl(0, "NeogitHunkHeaderHighlight", { bg = "#11262D", fg = "#f9cf79" })

